### ISSUE TITLE
UML classes with equally named attributes

### ISSUE THREAD

**Issue by bartkl** [henrietteharmse/uml2semantics#9]
Hello Henriette,

I'm trying to generate either LinkML schemas or OWL ontologies from a UML model from Sparx Enterprise Architect. For the sake of simplicity (and without loss of generality) I'll assume I'mg going to generate OWL.

First of all thank you for your [UML Class Diagram to OWL and SROIQ Reference](https://henrietteharmse.com/wp-content/uploads/2017/11/uml-class-diagram-to-owl-and-sroiq-reference.pdf), which is really helpful!

One fundamental issue I've come across that doesn't seem to be covered by that reference though is how to map class attributes onto OWL datatype properties. It seems trivial, but it gets tricky when you consider multiple classes with an equally named attribute. 

For example, say you have a `Person` class with an attribute `name`, and a class `Company` also with an attribute `name`. In UML, these attributes cannot be assumed to be identical, and following the Closed World Assumption can therefore be said to be different. Mapping such attributes to OWL properties should be done with caution, especially because of the inference semantics and first-class citizenship of properties.

I see two possible ways forward to map UML attributes to OWL datatype properties:

1. Respect the fact that equal names don't imply equal identity, and make sure you generate distinct datatype properties for each occurrence of an attribute, despite equal names. To resolve the name clashes, you could prefix the resulting property name with the class name. In the example this would yield (for example) `:Person.name` with domain `:Person` and `:Company.name` with domain `:Company`. This feels like the most safe and correct mapping, but it's also very ugly.
2. Create a datatype property `:name` and have its domain be equal to the most general superset of all classes. This is well-defined because in the worst case there's always `owl:Thing` or `rdfs:Resource` (I'd have to refresh my theory here). Although this looks nicer, it does make assumptions you cannot ground, namely that equally named attributes across classes are identical, something (as we saw) that's not the case in the original UML.

Honestly, I cannot justify 2 from a semantic perspective. 1, on the other hand, tells me OWL simply isn't the right target metamodel for having my UML expressed in. Please note that the underlying problem I'm trying to solve is to export the UML model from Enterprise Architect to a human and machine readable code representation that supports Linked Data (URIs).

I really struggle with this. How would you go about it? Really curious to hear your thoughts.

Thanks!

PS This question may touch on #4, but it's a different question ultimately.

**Comment by henrietteharmse** [comment]
Hi @bartkl! Thanks for the question!

It really depends on the purpose for translating UML to OWL. 

The original reason for translating UML to OWL was to find logical errors in the UML design and, since UML is often used for specifying requirements for software systems, finding these logical errors meant that these could be fixed before software development started, thereby reducing the cost of development.  Of course your translation (1) supports finding logical errors, but translation (2) is useful when you are interested in finding various cohesion related modelling violations. In my [dissertation on translating UML class diagrams to find modelling errors](https://henrietteharmse.com/wp-content/uploads/2019/09/scenariotestingusingowl_v0-1-7-final.pdf) I explain these modelling violations from a UML perspective in Section 2.2 on p. 21 and in Chapter 7 p.119 I explain how one can find these errors using OWL. However, strictly speaking these cohesion related errors can also be found using, for example, XPath queries on the XMI file.

Your translation (1) captures the semantics of UML classes with attributes exactly. In fact, in UML the QName for a `name` attribute of the `Person` class is `Person::name`. Hence, translating this in OWL to `Person.name` is indeed semantically correct, even if it rather clunky as you pointed out. In this translation it probably makes sense have disjointness statement between `Person.name` and `Company.name`. 

So what is my recommendation?
If you are not interested in finding modelling errors, go with translation (1). If you want find cohesion related modelling errors, initially go with translation (2) and fix the modelling errors, and then go with translation (1).

As your concern here relates to URIs, having your URIs include the class name is indeed sensible as your users will need to distinguish between `Person.name` and `Company.name`. My URI suggestion will be to use https://domain_name/Person#name or https://domain_name/Person/name. 

I hope this helps. If you want to discuss, I happy to setup a call.

**Comment by bartkl** [comment]
Thanks for your clear response, it's really helpful. I guess I should stick with (1) for my purposes then.

> In this translation it probably makes sense have disjointness statement between `Person.name` and `Company.name`

Yes indeed, sharp :).

I'll close the issue now. If I every do have follow up questions I'll keep the offer of a call in the back of my head.
Thanks!
